name: JSON File Creation

on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.10.0
      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: colors.json
          write-mode: overwrite
      - name: Run Python Script
        run: python ./.github/workflows/create-json.py
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
